var oldJCSini = ";\n\
; Texture effects\n\
;\n\
[Textures]\n\
0=Warp Horizon (Back Layer)         |Fade Red  |Fade Green |Fade Blue\n\
\n\
;\n\
; Tile type descriptions\n\
;\n\
[Tiles]\n\
1=Translucent\n\
4=Caption\n\
\n\
;\n\
; Events and parameters descriptions\n\
;\n\
[Events]\n\
0=(none)                            |+|abc       |No     |Event\n\
1=One Way                           |+|Modifier  |One    |Way\n\
2=Hurt                              |+|Modifier  |Hurt\n\
3=Vine                              |+|Modifier  |Vine\n\
4=Hook                              |+|Object    |Hook\n\
5=Slide                             |+|Modifier  |Slide\n\
6=H-Pole                            |+|Object    |H-Pole\n\
7=V-Pole                            |+|Object    |V-Pole\n\
8=Area Fly Off                      |+|Modifier  |Fly    |Off\n\
9=Ricochet                          |+|Modifier  |Rico   |chet\n\
10=Belt Right                       |+|Modifier  |Belt   |Right  |Speed:-8\n\
11=Belt Left                        |+|Modifier  |Belt   |Left   |Speed:-8\n\
12=Acc Belt R                       |+|Modifier  |Belt   |AccR   |Speed:-8\n\
13=Acc Belt L                       |+|Modifier  |Belt   |AccL   |Speed:-8\n\
14=Stop Enemy                       |+|Modifier  |Stop   |Enemy\n\
15=Wind Left                        |+|Modifier  |Wind   |Left   |Speed:-8\n\
16=Wind Right                       |+|Modifier  |Wind   |Right  |Speed:-8\n\
17=Area End Of Level                |+|Area      |End    |Area   |Secret:1\n\
18=Area Warp EOL                    |+|Area      |End    |Warp\n\
19=Area Revert Morph                |+|Area      |Revert |Morph\n\
20=Area Float Up                    |+|Area      |Float  |Up\n\
21=Trigger Rock                     |+|Trigger   |Trig   |Rock   |RockID:8\n\
22=Dim Light                        |+|Light     |Dim    |Light\n\
23=Set Light                        |+|Light     |Set    |Light  |Intensity:7|Red:-4|Green:-4|Blue:-4|Flicker:1\n\
24=Limit X Scroll                   |+|Modifier  |Stop   |Xscroll\n\
25=Reset Light                      |+|Light     |Reset  |Light\n\
26=Area Warp Secret                 |+|Area      |Warp   |Secret |Coins:10\n\
27=Echo                             |+|Sound     |Echo   |       |Amount:8\n\
28=Activate Boss                    |-|Boss      |Active |Boss|Music:1\n\
29=Jazz Level Start                 |+|StartPos  |Jazz   |Start  |Pos:4\n\
30=Spaz Level Start                 |+|StartPos  |Spaz   |Start  |Pos:4\n\
31=Multiplayer Level Start          |+|StartPos  |MP     |Start  |Team:1\n\
32=EMPTY                            |+|          |DON'T  |USE\n\
33=Freezer Ammo+3                   |+|Ammo      |Gun2   |Am+3\n\
34=Bouncer Ammo+3                   |+|Ammo      |Gun3   |Am+3\n\
35=Seeker Ammo+3                    |+|Ammo      |Gun4   |Am+3\n\
36=3Way Ammo+3                      |+|Ammo      |Gun5   |Am+3\n\
37=Toaster Ammo+3                   |+|Ammo      |Gun6   |Am+3\n\
38=TNT Ammo+3                       |+|Ammo      |TNT    |Am+3\n\
39=Gun8 Ammo+3                      |+|Ammo      |Gun8   |Am+3\n\
40=Gun9 Ammo+3                      |+|Ammo      |Gun9   |Am+3\n\
41=Still Turtleshell                |+|Object    |Turtle |Shell\n\
42=Swinging Vine                    |-|Object    |Swing  |Vine\n\
43=Bomb                             |+|Object    |Bomb\n\
44=Silver Coin                      |+|Goodies   |Silver |Coin\n\
45=Gold Coin                        |+|Goodies   |Gold   |Coin\n\
46=Gun crate                        |+|Ammo      |Gun    |Crate  |ExtraEvent:8|NumEvent:4|RandomFly:1\n\
47=Carrot crate                     |+|Goodies   |Carrot |Crate  |ExtraEvent:8|NumEvent:4|RandomFly:1\n\
48=1Up crate                        |+|Goodies   |1up    |Crate  |ExtraEvent:8|NumEvent:4|RandomFly:1\n\
49=Gem barrel                       |+|Gem       |Gem    |Barrel |Red:4|Green:4|Blue:4|Purple:4\n\
50=Carrot barrel                    |+|Goodies   |Carrot |Barrel\n\
51=1up barrel                       |+|Goodies   |1up    |Barrel\n\
52=Bomb Crate                       |+|Goodies   |Bomb   |Crate  |ExtraEvent:8|NumEvent:4|RandomFly:1\n\
53=Freezer Ammo+15                  |+|Ammo      |Gun2   |Am+15\n\
54=Bouncer Ammo+15                  |+|Ammo      |Gun3   |Am+15\n\
55=Seeker Ammo+15                   |+|Ammo      |Gun4   |Am+15\n\
56=3Way Ammo+15                     |+|Ammo      |Gun5   |Am+15\n\
57=Toaster Ammo+15                  |+|Ammo      |Gun6   |Am+15\n\
58=TNT (armed explosive, no pickup) |+|Object    |TNT\n\
59=Airboard                         |-|Object    |Air    |Board\n\
60=Frozen Green Spring              |+|Spring    |Frozen |Spring |Ceiling:1|Keep X-Speed:1|Keep Y-Speed:1|Delay (secs):4\n\
61=Gun Fast Fire                    |+|PowerUp   |Fast   |Fire\n\
62=Spring Crate                     |+|Spring    |Spring |Crate  |ExtraEvent:8|NumEvent:4|RandomFly:1\n\
63=Red Gem +1                       |+|Gem       |Red    |Gem\n\
64=Green Gem +1                     |+|Gem       |Green  |Gem\n\
65=Blue Gem +1                      |+|Gem       |Blue   |Gem\n\
66=Purple Gem +1                    |+|Gem       |Purple |Gem\n\
67=Super Red Gem                    |+|Gem       |Super  |Gem\n\
68=Birdy                            |-|Object    |Bird   |       |Chuck:1\n\
69=Gun Barrel                       |+|Ammo      |Gun    |Barrel\n\
70=Gem Crate                        |+|Gem       |Gem    |Crate  |Red:4|Green:4|Blue:4|Purple:4\n\
71=Jazz<->Spaz                      |+|Morph     |Jazz   |Spaz\n\
72=Carrot Energy +1                 |+|Goodies   |Carrot\n\
73=Full Energy                      |+|Goodies   |Full   |NRG\n\
74=Fire Shield                      |+|Shield    |Shield |Fire\n\
75=Water Shield                     |+|Shield    |Shield |Water\n\
76=Lightning Shield                 |+|Shield    |Shield |Light\n\
77=Max weapon                       |+|PowerUp   |Max    |Weapon\n\
78=Auto fire                        |+|PowerUp   |Auto   |Fire\n\
79=Fast Feet                        |+|Goodies   |Fast   |Feet\n\
80=Extra Live                       |+|Goodies   |Extra  |Live\n\
81=End of Level signpost            |-|SignPost  |End    |Level  |Secret:1\n\
82=EMPTY                            |+|          |DON'T  |USE\n\
83=Save point signpost              |+|SignPost  |Save   |Point\n\
84=Bonus Level signpost             |-|SignPost  |Bonus  |Level\n\
85=Red Spring                       |+|Spring    |Red    |Spring |Ceiling:1|Keep X-Speed:1|Keep Y-Speed:1|Delay (secs):4\n\
86=Green Spring                     |+|Spring    |Green  |Spring |Ceiling:1|Keep X-Speed:1|Keep Y-Speed:1|Delay (secs):4\n\
87=Blue Spring                      |+|Spring    |Blue   |Spring |Ceiling:1|Keep X-Speed:1|Keep Y-Speed:1|Delay (secs):4\n\
88=Invincibility                    |+|Goodies   |Invinc\n\
89=Extra Time                       |+|Goodies   |Extra  |Time\n\
90=Freeze Enemies                   |+|Goodies   |Freeze\n\
91=Hor Red Spring                   |+|Spring    |H-Red  |Spring |Empty:1|Keep X-Speed:1|Keep Y-Speed:1|Delay:4\n\
92=Hor Green Spring                 |+|Spring    |H-Green|Spring |Empty:1|Keep X-Speed:1|Keep Y-Speed:1|Delay:4\n\
93=Hor Blue Spring                  |+|Spring    |H-Blue |Spring |Empty:1|Keep X-Speed:1|Keep Y-Speed:1|Delay:4\n\
94=Morph Into Bird                  |-|Morph     |Bird   |Morph\n\
95=Scenery Trigger Crate            |+|Trigger   |Trig   |Crate  |TriggerID:5\n\
96=Fly carrot                       |-|Goodies   |Flyy   |Boyy\n\
97=RectGem Red                      |+|Gem       |Red    |Gem2\n\
98=RectGem Green                    |+|Gem       |Green  |Gem2\n\
99=RectGem Blue                     |+|Gem       |Blue   |Gem2\n\
100=Tuf Turt                        |-|Enemy     |Tuf    |Turt\n\
101=Tuf Boss                        |-|Boss      |Tuf    |Boss   |EndText:4\n\
102=Lab Rat                         |-|Enemy     |Lab    |Rat\n\
103=Dragon                          |-|Enemy     |Dra-   |gon\n\
104=Lizard                          |-|Enemy     |Lizard\n\
105=Bee                             |-|Enemy     |Bum    |Bee\n\
106=Rapier                          |-|Enemy     |Rapier\n\
107=Sparks                          |-|Enemy     |Sparks\n\
108=Bat                             |-|Enemy     |Bat\n\
109=Sucker                          |-|Enemy     |Suckr\n\
110=Caterpillar                     |-|Enemy     |Cater  |Pillar\n\
111=Cheshire Cat 1                  |-|Object    |Chesh  |Cat1\n\
112=Cheshire Cat 2                  |-|Object    |Chesh  |Cat2   |Duration:8\n\
113=Hatter                          |-|Enemy     |Hatter\n\
114=Bilsy Boss                      |-|Boss      |Bilsy  |Boss   |EndText:4\n\
115=Skeleton                        |-|Enemy     |Skele- |ton\n\
116=Doggy Dogg                      |-|Enemy     |Doggy  |Dogg\n\
117=Normal Turtle                   |-|Enemy     |Norm   |Turt\n\
118=Helmut                          |-|Enemy     |Helmut\n\
119=Leaf                            |+|Object    |Leaf\n\
120=Demon                           |-|Enemy     |Demon\n\
121=Fire                            |+|Scenery   |Fire\n\
122=Lava                            |+|Scenery   |Lava\n\
123=Dragon Fly                      |-|Enemy     |Drag   |Fly\n\
124=Monkey                          |-|Enemy     |Mon-   |key\n\
125=Fat Chick                       |-|Enemy     |Fat    |Chick\n\
126=Fencer                          |-|Enemy     |Fencer\n\
127=Fish                            |-|Enemy     |Fish\n\
128=Moth                            |+|Scenery   |Moth   |Moth   |Type:3\n\
129=Steam                           |+|Scenery   |Steam\n\
130=Rotating Rock                   |-|Object    |Roll   |Rock   |RockID:8|X-Speed:-4|Y-Speed:-4\n\
131=Blaster PowerUp                 |+|PowerUp   |Blastr |Power\n\
132=Bouncy PowerUp                  |+|PowerUp   |Bounce |Power\n\
133=Ice gun PowerUp                 |+|PowerUp   |Ice    |Power\n\
134=Seek PowerUp                    |+|PowerUp   |Seek   |Power\n\
135=RF PowerUp                      |+|PowerUp   |RF     |Power\n\
136=Toaster PowerUP                 |+|PowerUp   |Toast  |Power\n\
137=PIN: Left Paddle                |-|Pinball   |Left   |Pad\n\
138=PIN: Right Paddle               |-|Pinball   |Right  |Pad\n\
139=PIN: 500 Bump                   |-|Pinball   |500    |Bump\n\
140=PIN: Carrot Bump                |-|Pinball   |Carrot |Bump\n\
141=Apple                           |+|Food      |Apple\n\
142=Banana                          |+|Food      |Bana-  |na\n\
143=Cherry                          |+|Food      |Cherry\n\
144=Orange                          |+|Food      |Orange\n\
145=Pear                            |+|Food      |Pear\n\
146=Pretzel                         |+|Food      |Pretzel\n\
147=Strawberry                      |+|Food      |Straw  |Berry\n\
148=Steady Light                    |+|Light     |Steady |Light\n\
149=Pulze Light                     |+|Light     |Pulze  |Light  |Speed:8|Sync:4\n\
150=Flicker Light                   |+|Light     |Flick  |Light  |Sample:8\n\
151=Queen Boss                      |-|Boss      |Boss   |Queen  |EndText:4\n\
152=Floating Sucker                 |-|Enemy     |Float  |Sucker\n\
153=Bridge                          |+|Object    |Bridge |       |Width (Tiles):4|Type:3|Toughness:4\n\
154=Lemon                           |+|Food      |Lemon\n\
155=Lime                            |+|Food      |Lime\n\
156=Thing                           |+|Food      |Thing\n\
157=Watermelon                      |+|Food      |Water  |Melon\n\
158=Peach                           |+|Food      |Peach\n\
159=Grapes                          |+|Food      |Grapes\n\
160=Lettuce                         |+|Food      |Let-   |tuce\n\
161=Eggplant                        |+|Food      |Egg    |Plant\n\
162=Cucumb                          |+|Food      |Cucumb\n\
163=Soft Drink                      |+|Food      |Soft|Drink\n\
164=Soda Pop                        |+|Food      |Soda|Pop\n\
165=Milk                            |+|Food      |Milk\n\
166=Pie                             |+|Food      |Pie\n\
167=Cake                            |+|Food      |Cake\n\
168=Donut                           |+|Food      |Donut\n\
169=Cupcake                         |+|Food      |Cup    |Cake\n\
170=Chips                           |+|Food      |Chips\n\
171=Candy                           |+|Food      |Candy\n\
172=Chocbar                         |+|Food      |Choc   |Bar\n\
173=Icecream                        |+|Food      |Ice    |Cream\n\
174=Burger                          |+|Food      |Burger\n\
175=Pizza                           |+|Food      |Pizza\n\
176=Fries                           |+|Food      |Fries\n\
177=Chicken Leg                     |+|Food      |Chickn |Leg\n\
178=Sandwich                        |+|Food      |Sand   |Wich\n\
179=Taco                            |+|Food      |Taco\n\
180=Weenie                          |+|Food      |Weenie\n\
181=Ham                             |+|Food      |Ham\n\
182=Cheese                          |+|Food      |Cheese\n\
183=Float Lizard                    |-|Enemy     |Float  |Lizard |Duration:8|Fly Away:1\n\
184=Stand Monkey                    |-|Enemy     |Stand  |Monkey\n\
185=Destruct Scenery                |+|Trigger   |Dest   |Scen   |Empty:10|SpeedDestr:5|Weapon:4\n\
186=Destruct Scenery BOMB           |+|Trigger   |Bomb   |Scen   |Empty:10|Empty:5|Empty:4\n\
187=Collapsing Scenery              |+|Trigger   |Collaps|Scen   |Wait:10|FPS:5|Empty:4\n\
188=ButtStomp Scenery               |+|Trigger   |Stomp  |Scen   |Empty:10|Empty:5|Empty:4\n\
189=Invisible GemStomp              |+|Gem       |Gem    |Stomp\n\
190=Raven                           |-|Enemy     |Raven\n\
191=Tube Turtle                     |-|Enemy     |Tube   |Turt\n\
192=Gem Ring                        |+|Gem       |Gem    |Ring   |Length:5|Speed:5\n\
193=Small Tree                      |+|Object    |Small  |Tree   |Adjust Y:5|Adjust X:-6\n\
194=Ambient Sound                   |+|Sound     |Ambient|Sound  |Sample:8|Amplify:8|Fade:1|Sine:1\n\
195=Uterus                          |-|Boss      |Uterus |Boss   |EndText:4\n\
196=Crab                            |-|Enemy     |Crab\n\
197=Witch                           |-|Enemy     |Witch\n\
198=Rocket Turtle                   |-|Enemy     |Rock   |Turt   |EndText:4\n\
199=Bubba                           |-|Boss      |Bubba  |Boss   |EndText:4\n\
200=Devil devan boss                |-|Boss      |Devil  |Devan  |EndText:4\n\
201=Devan (robot boss)              |-|Boss      |Devan  |Boss   |IntroText:4|EndText:4\n\
202=Robot (robot boss)              |-|Boss      |Robot  |Boss\n\
203=Carrotus pole                   |+|Object    |Carr   |Pole   |Adjust Y:5|Adjust X:-6\n\
204=Psych pole                      |+|Object    |Psych  |Pole   |Adjust Y:5|Adjust X:-6\n\
205=Diamondus pole                  |+|Object    |Diam   |Pole   |Adjust Y:5|Adjust X:-6\n\
206=Sucker Tube                     |+|Object    |Suck   |       |X-Speed:-7|Y-Speed:-7|Trig Sample:3|WaitTime:3\n\
207=Text                            |+|Trigger   |Text   |       |TextID:8|Vanish:1\n\
208=Water Level                     |+|Scenery   |Water  |       |Height (Tiles):8|Instant:1\n\
209=Fruit Platform                  |-|Platform  |Fruit  |Plat   |Sync:2|Speed:-6|Length:4|Swing:1\n\
210=Boll Platform                   |-|Platform  |Boll   |Plat   |Sync:2|Speed:-6|Length:4|Swing:1\n\
211=Grass Platform                  |-|Platform  |Grass  |Plat   |Sync:2|Speed:-6|Length:4|Swing:1\n\
212=Pink Platform                   |-|Platform  |Pink   |Plat   |Sync:2|Speed:-6|Length:4|Swing:1\n\
213=Sonic Platform                  |-|Platform  |Sonic  |Plat   |Sync:2|Speed:-6|Length:4|Swing:1\n\
214=Spike Platform                  |-|Platform  |Spike  |Plat   |Sync:2|Speed:-6|Length:4|Swing:1\n\
215=Spike Boll                      |-|Object    |Spike  |Boll   |Sync:2|Speed:-6|Length:4|Swing:1\n\
216=Generator                       |+|          |Gene-  |rator  |Event:8|Delay (secs):5\n\
217=Eva                             |-|Object    |Eva\n\
218=Bubbler                         |-|Scenery   |Bubb   |ler    |Speed:4\n\
219=TNT Powerup                     |+|PowerUp   |TNT    |Power\n\
220=Gun8 Powerup                    |+|PowerUp   |Gun8   |Power\n\
221=Gun9 Powerup                    |+|PowerUp   |Gun9   |Power\n\
222=Morph Frog                      |-|Morph     |Morph  |Frog\n\
223=3D Spike Boll                   |+|Object    |3D     |Boll   |Sync:2|Speed:-6|Length:4|Swing:1|Shade:1\n\
224=Springcord                      |-|Spring    |Spring |Cord\n\
225=Bees                            |-|Enemy     |Bees   |       |Num:8\n\
226=Copter                          |+|Object    |Copter |       |Duration:8\n\
227=Laser Shield                    |-|Shield    |Laser  |Shield\n\
228=Stopwatch                       |-|Object    |Stop   |Watch\n\
229=Jungle Pole                     |+|Object    |Jung   |Pole   |Adjust Y:5|Adjust X:-6\n\
230=Warp                            |+|Area      |Warp   |       |ID:8|Coins:8|SetLap:1|ShowAnim:1\n\
231=Big Rock                        |+|Object    |Big    |Rock\n\
232=Big Box                         |+|Object    |Big    |Box\n\
233=Water Block                     |+|Scenery   |Water  |Block  |Adjust Y:-8\n\
234=Trigger Scenery                 |+|Trigger   |Trig   |Scen   |TriggerID:5\n\
235=Bolly Boss                      |-|Boss      |Bolly  |Boss\n\
236=Butterfly                       |-|Enemy     |Butter |Fly\n\
237=BeeBoy                          |-|Enemy     |Bee    |Boy    |Swarm:8\n\
238=Snow                            |+|Scenery   |Snow   |Particles\n\
239=EMPTY                           |+|          |DON'T  |USE\n\
240=Warp Target                     |+|Area      |Warp   |Target |ID:8\n\
241=Tweedle Boss                    |-|Boss      |Tweedle|Boss\n\
242=Area Id                         |+|Area      |Area   |ID     |ID:8\n\
243=EMPTY                           |+|          |DON'T  |USE\n\
244=CTF Base + Flag                 |+|Object    |CTF    |Base   |Team:1|Direction:1\n\
245=No Fire Zone                    |+|Area      |No Fire|Zone\n\
246=Trigger Zone                    |+|Area      |Trigger|Zone|TriggerID:5|onoff:1|switch:1\n\
247=Xmas Bilsy Boss                 |-|Boss      |XMBilsy|Boss   |EndText:4\n\
248=Xmas Norm Turtle                |-|Enemy     |XMNorm|Turt\n\
249=Xmas Lizard                     |-|Enemy     |XMLizard\n\
250=Xmas Float Lizard               |-|Enemy     |XMFloat|Lizard |Duration:8|Fly Away:1\n\
251=Addon DOG                       |-|Enemy     |Addon|Dog\n\
252=Addon Sparks                    |-|Enemy     |Addon|Sparks\n\
253=EMPTY                           |+|          |DON'T  |USE\n\
254=EMPTY                           |+|          |DON'T  |USE\n\
255=MCE Event                       |+|Modifier  |MCE    |Event";